version: '3'
include:
  - communication/docker-compose.yml

services:
  sensor-alert-1:
    build:
      context: ./sensor/alert
      dockerfile: Dockerfile
    container_name: sensor-alert-1
    depends_on:
      - kafka
      - zookeeper
    restart: always
    networks:
      - kafka_default

  sensor-system-1:
    build:
      context: ./sensor/SensorSystem
      dockerfile: Dockerfile
    container_name: sensor-system-1
    restart: always
    depends_on:
      - kafka
      - zookeeper
    networks:
      - kafka_default

  sensor-system-2:
    build:
      context: ./sensor/SensorSystem
      dockerfile: Dockerfile
    container_name: sensor-system-2
    restart: always
    depends_on:
      - kafka
      - zookeeper
    networks:
      - kafka_default

  sensor-system-3:
    build:
      context: ./sensor/SensorSystem
      dockerfile: Dockerfile
    container_name: sensor-system-3
    restart: always
    depends_on:
      - kafka
      - zookeeper
    networks:
      - kafka_default
