version: '3'
include:
  - communication/docker-compose.yml

services:
  sensor-alert:
    build:
      context: ./sensor/alert
      dockerfile: Dockerfile
    container_name: sensor-alert
    depends_on:
      - kafka
      - zookeeper
    restart: always
    networks:
      - kafka_default

  sensor-system:
    build:
      context: ./sensor/SensorSystem
      dockerfile: Dockerfile
    container_name: sensor-system
    depends_on:
      - kafka
      - zookeeper
    networks:
      - kafka_default

  sensor-system-2:
    build:
      context: ./sensor/SensorSystem
      dockerfile: Dockerfile
    container_name: sensor-system-2
    depends_on:
      - kafka
      - zookeeper
    networks:
      - kafka_default
